### ISSUE TITLE
Убрать лишнее из репозитория

### ISSUE THREAD

**Issue by pomponchik** [Revulo2605/yandex_api_stand_tests#1]
https://github.com/Revulo2605/yandex_api_stand_tests/blob/ddb056f25d701c7150785fba39cb11e90e636039/.gitignore#L5

Вы написали некоторые директории в игнор-листе, но не убрали их из репозитория, это выглядит неряшливо.

**Comment by Revulo2605** [comment]
Благодарю за внимательность. Убрал лишнее из репозитория
